name=AsyncTelnet
version=1.1.0
author=Frank Bösing
maintainer=Frank Bösing
sentence=Lightweight, non-blocking Telnet server for ESP32.
paragraph=An asynchronous Telnet server implementation for ESP32, useful for logging and remote terminal access without blocking the main loop.
category=Communication
url=https://github.com/FrankBoesing/AsyncTelnet.git
architectures=esp32
depends=AsyncTCP
